- name: Installing all commons
  gather_facts: false
  hosts:
    - all
  become: true
  roles:
    - role: docker-tools
      tags: tools
    - role: portainer-agent
      tags: portainer-agent
    - role: raspi-home-deploy
      tags: deploy